import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import Sidebar from "@/components/Sidebar";
import Navbar from "@/components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex bg-[#ededed] flex-row h-screen overflow-hidden">
          {/* Sidebar occupies space properly */}
          <Sidebar />
          <div className="flex-1 flex flex-col bg-[#0F0F0F] overflow-hidden">            {/* Navbar */}
            <Navbar />

            {/* Children Content with Scroll */}
            <div className="flex-1 overflow-y-auto p-6 md:px-9 pt-6 ">{children}</div>
          </div>
        </div>
      </body>
    </html>
  );
}
